-- Built for Biz — roster seed (generated from June_9.xlsx)
-- Run AFTER schema.sql. Re-running is safe: matches on email, updates in place.
insert into public.members (full_name, company, category, email, phone, is_admin) values
  ('Alyssa Crowder', 'Rainbow Systems', 'Authorized Rainbow Dealer', 'alyssapeardon@gmail.com', '(619) 699-9119', false),
  ('Anthony Calibeo', 'Integrity Wealth Consultants', 'Financial Advisor', 'acalibeo@integritywc.com', '(586) 651-2669', false),
  ('Brad Quail', 'First State Bank', 'Commercial Mortgages & Business Loans', 'bquail@fsb.bank', '(586) 873-8314', true),
  ('Casey Schiner', 'McGuffey Home Health Care', 'Home Health Care Services', 'casey@mcghhc.com', '(586) 713-0369', false),
  ('Chris Nelson', 'Serve YOU Electric', 'Electrician', 'chris@serveyouelectric.com', '(586) 219-6443', false),
  ('Cliff Clore', 'Custom Digtal Solutions', 'Digital Advertising', 'customdigitalsales@gmail.com', '(586) 217-1400', false),
  ('Dave Grimes', 'Owner - Sweetwaters Coffee and Tea', 'Sweetwaters Coffee and Tea', 'daveg@swlakesideshelby.com', '(586) 522-2322', false),
  ('Diane Mercurio', 'DuoCare Cleaning and Restoration', 'Carpet Cleaning', 'duocare.diane@gmail.com', '(586) 215-4149', false),
  ('Douglas B. Kelly', '5by5 Design', 'Graphic and Website Design', 'dkelly@5by5dzign.com', '(586) 381-2953', false),
  ('Frank Mercurio', 'Gompers, Cornish & Barr', 'Commercial Insurance', 'fmercurio@gcbinsurance.com', '(586) 630-3378', false),
  ('Gerard Giacona', 'Filipo Marc Winery', 'Winery and Gifts', 'fmwinery@gmail.com', '(586) 226-3990', true),
  ('Jackie McDonnell', 'First State Bank', 'Branch Manager', 'jmcdonnell@fsb.bank', '(586) 447-4834', false),
  ('Jeremy Harman', 'Great Lakes Landscape Design', 'Landscape Design', 'jharman@greatlakeslandscapedesign.com', '(586) 864-0029', false),
  ('Josette Drobek', 'Josette’s Travels', 'Travel Services', 'josettetravels@sbcglobal.net', '(586) 524-5867', false),
  ('Kalyan Rachakonda', 'Transworld Business Advisors of Sterling Heights', 'Business Brokerage', 'krachakonda@tworld.com', '(812) 341-7515', false),
  ('Keith Spicer', 'VOIP Services of Michigan', '', 'keith@voipservicesofmchgan.com', '248-301-9100', false),
  ('Ken Benando', '5 Pointe Window Cleaning', 'Window Cleaning', 'cbenando@aol.com', '(586) 731-3237', false),
  ('Kenneth LaBeau', 'Custom Insurance Agency, Inc.', 'Insurance', 'klabeau@custominsuranceagency.com', '(586) 935-6110', false),
  ('Kimberly Morse', 'Aesthetics Lounge and Spa', 'Spa Owner', 'kim@tal-spa.com', '(586) 530-8824', false),
  ('Marcus Palazzolo', 'Safety King, Inc.', 'Duct Cleaning', 'marcus@safetyking.com', '(586) 731-4720', false),
  ('Melton Eason', 'Real Estate One', 'Realtor', 'meason@realestateone.com', '(586) 224-8701', false),
  ('Michael Abdelnour', 'Union Home Mortgage', 'Mortgages', 'mikeabd2@gmail.com', '(586) 770-0997', true),
  ('Michael Filliccia', 'Filliccia Insurance Agency', 'Health Insurance', 'michael@fillicciainsurance.com', '(248) 537-4040', false),
  ('Mike Mattei', 'Social Boost of Michigan', 'AI and Social Media', 'Michael@socialboostsemi.com', '(248) 761-2262', false),
  ('Monica Staley', 'Accurate Pay Systems', 'Payroll Services', 'monica@accupayinc.com', '(586) 625-7597', false),
  ('Naomi Trotto', 'BA Salon Collective', 'Stylist', 'naomitrotto@gmail.com', '(586) 206-6822', false),
  ('Rebecca Wilson', 'The Dobrusin Law Firm', 'Patents / Trademark / Copyright', 'bwilson@patentco.com', '(248) 292-2920', false),
  ('Richard Giltz', 'House Professor', 'Home & Commercial Property Inspections', 'rgiltz@houseprofessor.com', '(586) 739-1909', false),
  ('Scott Bentas', 'Michigan Department of Labor and Economic Opportunity', '', 'bentass@michigan.gov', '(586) 942-5452', false),
  ('Sheila Kloski', 'BB Trophy & Awards', 'Plaques, Trophies, Name Badges', 'sheilak@bbtrophy.com', '(586) 216-0487', false),
  ('Steven Grifka', 'Richards Painting of Macomb', 'Painting', 'richardspaintingmacomb@gmail.com', '(586) 544-7840', false),
  ('Tom Lipinski', 'Everest Performance Coaching', 'Life/Business Coach; Change Consulting', 'tom@everest.coach', '(586) 246-6606', false),
  ('Tom Steger', 'Safe & Sound Home Repair LLC', 'Handyman & Home Repair', 'tom.steger@safesoundhomerepair.com', '(248) 721-4125', false)
on conflict (email) do update set
  full_name = excluded.full_name,
  company   = excluded.company,
  category  = excluded.category,
  phone     = excluded.phone,
  is_admin  = excluded.is_admin;
